Resources:
    ProductsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: products
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
            Tags:
                - Key: Service
                  Value: sls-ecommrce

    OrdersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: orders
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: orderId
                  AttributeType: S
                - AttributeName: userId
                  AttributeType: S
            KeySchema:
                - AttributeName: orderId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: userIdIndex
                  KeySchema:
                      - AttributeName: userId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            Tags:
                - Key: Service
                  Value: sls-ecommrce

    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: users
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
            Tags:
                - Key: Service
                  Value: sls-ecommrce
