createProduct:
    handler: src/services/products/handlers/createProduct.handler
    events:
        - httpApi:
              method: post
              path: /products
              authorizer: jwtAuthorizer
getProduct:
    handler: src/services/products/handlers/getProduct.handler
    events:
        - httpApi:
              method: get
              path: /products/{id}

listProduct:
    handler: src/services/products/handlers/listProduct.handler
    events:
        - httpApi:
              method: get
              path: /products

updateProduct:
    handler: src/services/products/handlers/updateProduct.handler
    events:
        - httpApi:
              method: patch
              path: /products/{id}
              authorizer: jwtAuthorizer

deleteProduct:
    handler: src/services/products/handlers/deleteProduct.handler
    events:
        - httpApi:
              method: delete
              path: /products/{id}
              authorizer: jwtAuthorizer
